# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'circularbar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CircularBar(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(347, 343)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.circularProgressBarBase = QtWidgets.QFrame(self.centralwidget)
        self.circularProgressBarBase.setGeometry(QtCore.QRect(10, 10, 320, 320))
        self.circularProgressBarBase.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgressBarBase.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgressBarBase.setObjectName("circularProgressBarBase")
        self.circularProgress = QtWidgets.QFrame(self.circularProgressBarBase)
        self.circularProgress.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.circularProgress.setStyleSheet("QFrame{\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.74 rgba(255, 0, 127, 0), stop:0.741 rgba(85, 170, 255, 255));\n"
"\n"
"border-radius:150px;\n"
"}")
        self.circularProgress.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularProgress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularProgress.setObjectName("circularProgress")
        self.circularBg = QtWidgets.QFrame(self.circularProgressBarBase)
        self.circularBg.setGeometry(QtCore.QRect(10, 10, 300, 300))
        self.circularBg.setStyleSheet("QFrame{    \n"
"border-radius:150px;\n"
"background-color: rgba(77, 77, 127,120);\n"
"}")
        self.circularBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.circularBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.circularBg.setObjectName("circularBg")
        self.frame = QtWidgets.QFrame(self.circularProgressBarBase)
        self.frame.setGeometry(QtCore.QRect(30, 30, 260, 260))
        self.frame.setStyleSheet("QFrame{\n"
"border-radius:130px;\n"
"background-color: rgb(77, 77, 127);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(80, 220, 98, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;\n"
"background-color: none;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_description = QtWidgets.QLabel(self.frame)
        self.label_description.setGeometry(QtCore.QRect(43, 190, 168, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.label_description.setFont(font)
        self.label_description.setStyleSheet("QLabel\n"
"{\n"
"border-radius:10px;\n"
"color:white;\n"
"background-color: rgb(118, 118, 177);\n"
"margin-left:40px;\n"
"margin-right:40px;\n"
"}")
        self.label_description.setAlignment(QtCore.Qt.AlignCenter)
        self.label_description.setObjectName("label_description")
        self.label_name = QtWidgets.QLabel(self.frame)
        self.label_name.setGeometry(QtCore.QRect(50, 40, 163, 25))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_name.setFont(font)
        self.label_name.setStyleSheet("color:white;\n"
"background-color: none;")
        self.label_name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name.setObjectName("label_name")
        self.label_value = QtWidgets.QLabel(self.frame)
        self.label_value.setGeometry(QtCore.QRect(30, 70, 241, 111))
        font = QtGui.QFont()
        font.setFamily("Roboto Thin")
        font.setPointSize(60)
        self.label_value.setFont(font)
        self.label_value.setStyleSheet("color:white;\n"
"background-color: none;")
        self.label_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value.setObjectName("label_value")
        self.circularBg.raise_()
        self.circularProgress.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#aaaaff;\">by </span><span style=\" color:#8484c6;\">Xenatronics</span></p></body></html>"))
        self.label_description.setText(_translate("MainWindow", "chargement..."))
        self.label_name.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600; color:#aaaaff;\">YOUR</span><span style=\" font-size:11pt;\"> APPLICATION</span></p></body></html>"))
        self.label_value.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:56pt; color:#ffffff;\">0</span><span style=\" font-size:48pt; color:#ffffff; vertical-align:super;\">%</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_CircularBar()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
